name: Build/release

on:
  push:
    tags:
    - '*'
        
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [macos-latest]
        # os: [windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Andy experiments
        run: |
          echo hello
          ls
          pwd
          node --version
          echo "that is all for now Andy"

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install npm stuff by Andy
        run: |
          echo hello
          npm install

      - name: Build/release Electron app
        # uses: samuelmeuli/action-electron-builder@v1
        uses: wixplosives/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          publish_cmd: "electron-builder"

